version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_KEY=your-secret-key-change-this
      - DATABASE_URL=sqlite:///./rag_app.db
      - OLLAMA_BASE_URL=http://localhost:11434
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge 